# Basic information
baseURL = "https://pengjiz.com"
title = "HeArt"
author = { name = "Pengji Zhang", email = "me@pengjiz.com" }

# Generator configuration
theme = "simple"
languageCode = "en"
hasCJKLanguage = true
paginate = 10
disableKinds = [ "taxonomy", "taxonomyTerm" ]
footnoteReturnLinkContents = "[Back]"
[markup]
  [markup.highlight]
    noClasses = false

# Additional parameters
[params]
  logoURL = "media/images/logo.png"
  blogSections = [ "zh", "en" ]
  [params.socials]
    github = "pengjiz"
