# Basic configuration
baseURL = "https://pengjiz.com"
title = "HeArt"
theme = "simple"
languageCode = "en"
hasCJKLanguage = true
paginate = 10
disableKinds = [ "taxonomy", "taxonomyTerm" ]
footnoteReturnLinkContents = "[Back]"

# Author information
[author]
name = "Pengji Zhang"
email = "me@pengjiz.com"

# Syntax highlighting
[markup.highlight]
noClasses = false

# Additional parameters
[params]
logoURL = "media/images/logo.png"
blogSections = [ "zh", "en" ]

## Social accounts
[params.socials]
github = "pengjiz"
